// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Version info; also proves the IPC pipeline end to end. */
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	platformInfo: () => typedError<PlatformInfo, AppError>(__TAURI_INVOKE("platform_info")),
	/**  Lets the Android back handler close the app ("press back again to exit"). */
	appExit: () => typedError<null, AppError>(__TAURI_INVOKE("app_exit")),
	/**  Opens an https URL of a known forge in the system browser. */
	appOpenUrl: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("app_open_url", { url })),
	gitIdentityGet: () => typedError<GitIdentity, AppError>(__TAURI_INVOKE("git_identity_get")),
	gitIdentitySet: (name: string, email: string) => typedError<GitIdentity, AppError>(__TAURI_INVOKE("git_identity_set", { name, email })),
	repoOpen: (path: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("repo_open", { path })),
	repoInit: (request: InitRequest) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("repo_init", { request })),
	repoClone: (request: CloneRequest) => typedError<string, AppError>(__TAURI_INVOKE("repo_clone", { request })),
	repoClose: (repo: string) => typedError<null, AppError>(__TAURI_INVOKE("repo_close", { repo })),
	repoInfo: (repo: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("repo_info", { repo })),
	repoRecent: () => typedError<RecentRepo[], AppError>(__TAURI_INVOKE("repo_recent")),
	/**  Deletes a repository folder under the default repos dir (mobile/embedded). */
	repoDelete: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("repo_delete", { path })),
	repoKnown: () => typedError<KnownRepo[], AppError>(__TAURI_INVOKE("repo_known")),
	repoForget: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("repo_forget", { path })),
	graphLoad: (repo: string, filter: GraphFilter) => typedError<GraphMeta, AppError>(__TAURI_INVOKE("graph_load", { repo, filter })),
	graphRows: (repo: string, start: number, len: number) => typedError<GraphRow[], AppError>(__TAURI_INVOKE("graph_rows", { repo, start, len })),
	graphSearch: (repo: string, search: GraphSearch) => typedError<number[], AppError>(__TAURI_INVOKE("graph_search", { repo, search })),
	/**  Row index of `oid` in the currently loaded graph, `None` when it is filtered out. */
	graphFind: (repo: string, oid: string) => typedError<number | null, AppError>(__TAURI_INVOKE("graph_find", { repo, oid })),
	commitDetails: (repo: string, oid: string) => typedError<CommitDetails, AppError>(__TAURI_INVOKE("commit_details", { repo, oid })),
	commitFileDiff: (repo: string, oid: string, path: string, options: DiffOptions) => typedError<FileDiff, AppError>(__TAURI_INVOKE("commit_file_diff", { repo, oid, path, options })),
	refsList: (repo: string) => typedError<RefsSnapshot, AppError>(__TAURI_INVOKE("refs_list", { repo })),
	branchCreate: (repo: string, request: BranchCreateRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("branch_create", { repo, request, dryRun })),
	branchDelete: (repo: string, request: BranchDeleteRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("branch_delete", { repo, request, dryRun })),
	branchRename: (repo: string, oldName: string, newName: string, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("branch_rename", { repo, oldName, newName, dryRun })),
	checkout: (repo: string, target: CheckoutTarget, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("checkout", { repo, target, dryRun })),
	tagCreate: (repo: string, request: TagCreateRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("tag_create", { repo, request, dryRun })),
	tagDelete: (repo: string, name: string, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("tag_delete", { repo, name, dryRun })),
	refMove: (repo: string, request: RefMoveRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("ref_move", { repo, request, dryRun })),
	status: (repo: string) => typedError<StatusSnapshot, AppError>(__TAURI_INVOKE("status", { repo })),
	worktreeFileDiff: (repo: string, path: string, staged: boolean, options: DiffOptions) => typedError<FileDiff, AppError>(__TAURI_INVOKE("worktree_file_diff", { repo, path, staged, options })),
	stagePaths: (repo: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_paths", { repo, paths })),
	unstagePaths: (repo: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_paths", { repo, paths })),
	discardPaths: (repo: string, paths: string[], dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("discard_paths", { repo, paths, dryRun })),
	stageLines: (repo: string, selection: LineSelection) => typedError<null, AppError>(__TAURI_INVOKE("stage_lines", { repo, selection })),
	unstageLines: (repo: string, selection: LineSelection) => typedError<null, AppError>(__TAURI_INVOKE("unstage_lines", { repo, selection })),
	discardLines: (repo: string, selection: LineSelection, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("discard_lines", { repo, selection, dryRun })),
	commitCreate: (repo: string, request: CommitRequest) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("commit_create", { repo, request })),
	stashList: (repo: string) => typedError<StashEntry[], AppError>(__TAURI_INVOKE("stash_list", { repo })),
	stashSave: (repo: string, request: StashSaveRequest) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("stash_save", { repo, request })),
	stashApply: (repo: string, index: number, pop: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("stash_apply", { repo, index, pop })),
	stashDrop: (repo: string, index: number, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("stash_drop", { repo, index, dryRun })),
	merge: (repo: string, request: MergeRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("merge", { repo, request, dryRun })),
	rebase: (repo: string, request: RebaseRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("rebase", { repo, request, dryRun })),
	rebaseTodoLoad: (repo: string, base: string) => typedError<RebaseTodoItem[], AppError>(__TAURI_INVOKE("rebase_todo_load", { repo, base })),
	rebaseInteractive: (repo: string, request: InteractiveRebaseRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("rebase_interactive", { repo, request, dryRun })),
	cherryPick: (repo: string, request: CherryPickRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("cherry_pick", { repo, request, dryRun })),
	revert: (repo: string, request: RevertRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("revert", { repo, request, dryRun })),
	reset: (repo: string, request: ResetRequest, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("reset", { repo, request, dryRun })),
	sequencerControl: (repo: string, action: SequencerAction) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("sequencer_control", { repo, action })),
	conflictList: (repo: string) => typedError<FileChange[], AppError>(__TAURI_INVOKE("conflict_list", { repo })),
	conflictFile: (repo: string, path: string) => typedError<ConflictFile, AppError>(__TAURI_INVOKE("conflict_file", { repo, path })),
	conflictResolve: (repo: string, path: string, resolution: ConflictResolution) => typedError<null, AppError>(__TAURI_INVOKE("conflict_resolve", { repo, path, resolution })),
	remoteList: (repo: string) => typedError<RemoteInfo[], AppError>(__TAURI_INVOKE("remote_list", { repo })),
	remoteAdd: (repo: string, request: RemoteAddRequest) => typedError<RemoteInfo, AppError>(__TAURI_INVOKE("remote_add", { repo, request })),
	remoteRemove: (repo: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("remote_remove", { repo, name })),
	remoteRename: (repo: string, oldName: string, newName: string) => typedError<null, AppError>(__TAURI_INVOKE("remote_rename", { repo, oldName, newName })),
	remoteSetUrl: (repo: string, name: string, url: string, push: boolean) => typedError<null, AppError>(__TAURI_INVOKE("remote_set_url", { repo, name, url, push })),
	fetch: (repo: string, request: FetchRequest) => typedError<string, AppError>(__TAURI_INVOKE("fetch", { repo, request })),
	pull: (repo: string, request: PullRequest) => typedError<string, AppError>(__TAURI_INVOKE("pull", { repo, request })),
	push: (repo: string, request: PushRequest) => typedError<string, AppError>(__TAURI_INVOKE("push", { repo, request })),
	setUpstream: (repo: string, branch: string, upstream: string | null) => typedError<null, AppError>(__TAURI_INVOKE("set_upstream", { repo, branch, upstream })),
	credentialRespond: (requestId: string, value: string | null, remember: boolean) => typedError<null, AppError>(__TAURI_INVOKE("credential_respond", { requestId, value, remember })),
	credentialStore: (request: CredentialStoreRequest) => typedError<null, AppError>(__TAURI_INVOKE("credential_store", { request })),
	credentialClear: (host: string) => typedError<null, AppError>(__TAURI_INVOKE("credential_clear", { host })),
	submoduleList: (repo: string) => typedError<SubmoduleInfo[], AppError>(__TAURI_INVOKE("submodule_list", { repo })),
	submoduleUpdate: (repo: string, request: SubmoduleUpdateRequest) => typedError<string, AppError>(__TAURI_INVOKE("submodule_update", { repo, request })),
	worktreeList: (repo: string) => typedError<WorktreeInfo[], AppError>(__TAURI_INVOKE("worktree_list", { repo })),
	worktreeAdd: (repo: string, request: WorktreeAddRequest) => typedError<WorktreeInfo, AppError>(__TAURI_INVOKE("worktree_add", { repo, request })),
	worktreeRemove: (repo: string, path: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("worktree_remove", { repo, path, force })),
	blame: (repo: string, path: string, rev: string | null) => typedError<BlameResult, AppError>(__TAURI_INVOKE("blame", { repo, path, rev })),
	fileHistory: (repo: string, path: string, limit: number) => typedError<FileHistoryEntry[], AppError>(__TAURI_INVOKE("file_history", { repo, path, limit })),
	reflog: (repo: string, refName: string, limit: number) => typedError<ReflogEntry[], AppError>(__TAURI_INVOKE("reflog", { repo, refName, limit })),
	oplogList: (repo: string, limit: number) => typedError<OplogEntry[], AppError>(__TAURI_INVOKE("oplog_list", { repo, limit })),
	undo: (repo: string, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("undo", { repo, dryRun })),
	redo: (repo: string, dryRun: boolean) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("redo", { repo, dryRun })),
	opCancel: (opId: string) => typedError<null, AppError>(__TAURI_INVOKE("op_cancel", { opId })),
	oplogState: (repo: string) => typedError<OplogState, AppError>(__TAURI_INVOKE("oplog_state", { repo })),
	avatarsGet: (subjects: AvatarSubject[], size: number) => typedError<(string | null)[], AppError>(__TAURI_INVOKE("avatars_get", { subjects, size })),
	forgeStatus: (repo: string) => typedError<ForgeStatus, AppError>(__TAURI_INVOKE("forge_status", { repo })),
	forgeTokenSource: (host: string) => typedError<ForgeTokenSource, AppError>(__TAURI_INVOKE("forge_token_source", { host })),
	forgeTokenSet: (host: string, token: string) => typedError<ForgeUser, AppError>(__TAURI_INVOKE("forge_token_set", { host, token })),
	forgeTokenClear: (host: string) => typedError<null, AppError>(__TAURI_INVOKE("forge_token_clear", { host })),
	forgeIssues: (repo: string, query: IssueQuery) => typedError<IssuePage, AppError>(__TAURI_INVOKE("forge_issues", { repo, query })),
	forgeIssue: (repo: string, number: number) => typedError<IssueDetail, AppError>(__TAURI_INVOKE("forge_issue", { repo, number })),
	forgeIssueCreate: (repo: string, request: IssueCreateRequest) => typedError<Issue, AppError>(__TAURI_INVOKE("forge_issue_create", { repo, request })),
	forgeIssueComment: (repo: string, number: number, body: string) => typedError<ForgeComment, AppError>(__TAURI_INVOKE("forge_issue_comment", { repo, number, body })),
	forgeCommitComments: (repo: string, oid: string) => typedError<ForgeComment[], AppError>(__TAURI_INVOKE("forge_commit_comments", { repo, oid })),
	forgeCommitComment: (repo: string, oid: string, body: string) => typedError<ForgeComment, AppError>(__TAURI_INVOKE("forge_commit_comment", { repo, oid, body })),
	forgePulls: (repo: string, query: PullQuery) => typedError<PullPage, AppError>(__TAURI_INVOKE("forge_pulls", { repo, query })),
	forgePull: (repo: string, number: number) => typedError<PullDetail, AppError>(__TAURI_INVOKE("forge_pull", { repo, number })),
	forgePullComment: (repo: string, number: number, body: string) => typedError<ForgeComment, AppError>(__TAURI_INVOKE("forge_pull_comment", { repo, number, body })),
	forgeNotifications: (host: string) => typedError<ForgeNotification[], AppError>(__TAURI_INVOKE("forge_notifications", { host })),
	sshKeysList: () => typedError<SshKeyList, AppError>(__TAURI_INVOKE("ssh_keys_list")),
	sshKeyGenerate: (request: SshKeyGenerateRequest) => typedError<SshKey, AppError>(__TAURI_INVOKE("ssh_key_generate", { request })),
	terminalOpen: (request: TerminalOpenRequest) => typedError<string, AppError>(__TAURI_INVOKE("terminal_open", { request })),
	terminalWrite: (id: string, data: string) => typedError<null, AppError>(__TAURI_INVOKE("terminal_write", { id, data })),
	terminalResize: (id: string, cols: number, rows: number) => typedError<null, AppError>(__TAURI_INVOKE("terminal_resize", { id, cols, rows })),
	terminalClose: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("terminal_close", { id })),
	aiSettingsGet: () => typedError<AiSettings, AppError>(__TAURI_INVOKE("ai_settings_get")),
	aiSettingsSet: (settings: AiSettings) => typedError<AiSettings, AppError>(__TAURI_INVOKE("ai_settings_set", { settings })),
	aiKeySet: (provider: AiProviderKind, key: string) => typedError<null, AppError>(__TAURI_INVOKE("ai_key_set", { provider, key })),
	aiKeyClear: (provider: AiProviderKind) => typedError<null, AppError>(__TAURI_INVOKE("ai_key_clear", { provider })),
	aiPayloadPreview: (repo: string, request: AiRequest) => typedError<AiPayloadPreview, AppError>(__TAURI_INVOKE("ai_payload_preview", { repo, request })),
	aiRun: (repo: string, request: AiRequest) => typedError<AiResponse, AppError>(__TAURI_INVOKE("ai_run", { repo, request })),
	aiPlanExecute: (repo: string, planId: string) => typedError<OpOutcome, AppError>(__TAURI_INVOKE("ai_plan_execute", { repo, planId })),
	settingsGet: () => typedError<AppSettings, AppError>(__TAURI_INVOKE("settings_get")),
	settingsSet: (settings: AppSettings) => typedError<AppSettings, AppError>(__TAURI_INVOKE("settings_set", { settings })),
	keybindingsGet: () => typedError<Keybinding[], AppError>(__TAURI_INVOKE("keybindings_get")),
	keybindingsSet: (bindings: Keybinding[]) => typedError<Keybinding[], AppError>(__TAURI_INVOKE("keybindings_set", { bindings })),
};

/** Events */
export const events = {
	credentialRequested: makeEvent<CredentialRequested>("credential-requested"),
	opFinished: makeEvent<OpFinished>("op-finished"),
	opProgress: makeEvent<OpProgress>("op-progress"),
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
	terminalExit: makeEvent<TerminalExit>("terminal-exit"),
	terminalOutput: makeEvent<TerminalOutput>("terminal-output"),
};

/* Types */
export type AiPayloadPreview = {
	bytes: number,
	files: string[],
	truncated: boolean,
	/**  The exact text that would be sent. */
	content: string,
};

export type AiPlan = {
	id: string,
	prompt: string,
	explanation: string,
	steps: PlannedStep[],
	preview: OpPreview,
};

export type AiProviderKind = "anthropic" | "openAiCompatible";

export type AiRequest = { kind: "commitMessage" } | { kind: "conflictSuggestion"; path: string } | { kind: "summarize"; target: SummaryTarget } | { kind: "prDescription"; base: string; head: string } | { kind: "plan"; prompt: string };

export type AiResponse = { kind: "text"; text: string } | { kind: "plan"; plan: AiPlan };

export type AiSettings = {
	/**  Off by default; no repository content leaves the machine while false. */
	enabled: boolean,
	provider: AiProviderKind,
	model: string,
	baseUrl: string | null,
	maxDiffBytes: number,
	/**  Read-only: whether a key for `provider` is in the OS keychain. */
	hasKey: boolean,
};

/**  Error returned by every IPC command. */
export type AppError = {
	kind: ErrorKind,
	message: string,
	detail: string | null,
};

export type AppInfo = {
	version: string,
	/**  `git --version` output, `None` when git is not on PATH. */
	gitVersion: string | null,
	platform: string,
};

export type AppSettings = {
	theme: ThemePreference,
	/**  Custom git executable; `None` uses PATH. */
	gitPath: string | null,
	pullStrategy: PullStrategy,
	confirmDestructive: boolean,
	graphOrder: CommitOrder,
	diffContextLines: number,
	/**  Where avatars may be fetched from (by the backend; the webview never contacts avatar hosts). */
	avatars: AvatarMode,
	/**  Decorative gradients behind the graph and on the Home page. */
	backdrop: boolean,
	/**  Named groups of repository paths (Home page). */
	workspaces: Workspace[],
};

export type AvatarMode = "off" | "github" | "githubAndGravatar";

export type AvatarSubject = { kind: "email"; email: string } | { kind: "githubLogin"; login: string };

export type BlameHunk = {
	oid: string,
	authorName: string,
	authorTime: number | null,
	summary: string,
	/**  1-based first line in the final file. */
	startLine: number,
	lineCount: number,
	origPath: string,
};

export type BlameResult = {
	path: string,
	lines: string[],
	hunks: BlameHunk[],
};

export type BranchCreateRequest = {
	name: string,
	/**  Defaults to HEAD. */
	startPoint: string | null,
	checkout: boolean,
};

export type BranchDeleteRequest = {
	name: string,
	remote: boolean,
	force: boolean,
};

export type BranchInfo = {
	name: string,
	fullName: string,
	oid: string,
	upstream: string | null,
	ahead: number,
	behind: number,
	isHead: boolean,
	/**  Remote name for remote-tracking branches. */
	remote: string | null,
};

export type ChangeScope = "refs" | "index" | "worktree" | "config";

export type ChangeStatus = "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChange" | "untracked" | "conflicted";

export type CheckoutTarget = { kind: "branch"; name: string } | { kind: "commit"; oid: string } | 
/**  Creates `local_name` tracking `name` (e.g. `origin/feature`). */
{ kind: "remoteBranch"; name: string; localName: string };

export type CherryPickRequest = {
	commits: string[],
	/**  Branch to apply onto; checked out first when it is not HEAD. */
	targetBranch: string | null,
	noCommit: boolean,
};

export type CloneRequest = {
	url: string,
	dest: string,
	bare: boolean,
	recurseSubmodules: boolean,
};

export type CommitDetails = {
	oid: string,
	parents: string[],
	author: Signature,
	committer: Signature,
	summary: string,
	body: string,
	files: FileChange[],
	refs: RefLabel[],
};

export type CommitOrder = "topo" | "date";

export type CommitRequest = {
	message: string,
	amend: boolean,
	signOff: boolean,
	allowEmpty: boolean,
};

export type CommitSummary = {
	oid: string,
	shortOid: string,
	summary: string,
	authorName: string,
	authorTime: number | null,
};

export type ConflictFile = {
	path: string,
	binary: boolean,
	base: string | null,
	ours: string | null,
	theirs: string | null,
	/**  Working-tree content with conflict markers. */
	merged: string,
	oursLabel: string,
	theirsLabel: string,
};

export type ConflictResolution = { kind: "ours" } | { kind: "theirs" } | { kind: "content"; content: string };

export type CredentialKind = "username" | "password" | "passphrase";

/**  Git needs a credential; answer with `credential_respond`. */
export type CredentialRequested = {
	requestId: string,
	url: string,
	username: string | null,
	kind: CredentialKind,
};

export type CredentialStoreRequest = {
	host: string,
	username: string,
	secret: string,
};

export type DiffLine = {
	kind: LineKind,
	oldLineno: number | null,
	newLineno: number | null,
	content: string,
};

export type DiffOptions = {
	contextLines: number,
	ignoreWhitespace: boolean,
};

export type EdgeKind = 
/**  A lane continuing to the next row (`from_lane == to_lane`). */
"straight" | 
/**
 *  A line converging into an existing lane: joining a parent that is
 *  already reserved elsewhere, or a lane collapsing into the lane of
 *  the commit on the next row.
 */
"mergeIn" | 
/**  A non-first parent of this row's commit opening a new lane. */
"branchOut";

/**  Closed set of error categories the UI can branch on. */
export type ErrorKind = "notARepo" | "conflict" | "dirtyWorktree" | "authRequired" | "authFailed" | "network" | "refNotFound" | "invalidInput" | "gitCli" | "aiDisabled" | "aiProvider" | "cancelled" | "io" | "notImplemented" | "unsupported" | "internal";

export type FetchRequest = {
	/**  `None` fetches all remotes. */
	remote: string | null,
	prune: boolean,
	tags: boolean,
};

export type FileChange = {
	path: string,
	oldPath: string | null,
	status: ChangeStatus,
	additions: number,
	deletions: number,
	binary: boolean,
};

export type FileDiff = {
	path: string,
	oldPath: string | null,
	status: ChangeStatus,
	binary: boolean,
	hunks: Hunk[],
};

export type FileHistoryEntry = {
	commit: CommitSummary,
	/**  Path of the file at this commit (follows renames). */
	path: string,
	status: ChangeStatus,
};

export type ForgeComment = {
	/**  Forge id as a string (GitHub ids exceed u32). */
	id: string,
	author: ForgeUser,
	/**  Plain text as written (Markdown source); never rendered as HTML. */
	body: string,
	createdAt: number | null,
	url: string,
};

export type ForgeKind = "github" | "gitlab";

export type ForgeNotification = {
	id: string,
	title: string,
	/**  GitHub subject type: "Issue", "PullRequest", "Commit", "Release", "Discussion", ... */
	kind: string,
	/**  GitHub reason: "mention", "review_requested", "subscribed", ... */
	reason: string,
	/**  "owner/name" */
	repo: string,
	unread: boolean,
	updatedAt: number | null,
	/**  https://github.com/... page of the subject; None when unknown. */
	url: string | null,
};

export type ForgePull = {
	number: number,
	title: string,
	state: PullState,
	draft: boolean,
	author: ForgeUser,
	head: PullBranch,
	base: PullBranch,
	labels: string[],
	createdAt: number | null,
	updatedAt: number | null,
	/**  Web URL of the pull request. */
	url: string,
};

export type ForgeRepo = {
	kind: ForgeKind,
	/**  e.g. "github.com" */
	host: string,
	owner: string,
	name: string,
	/**  https://github.com/<owner>/<name> */
	webUrl: string,
	/**  Remote the repo was derived from, e.g. "origin". */
	remote: string,
};

export type ForgeStatus = {
	/**  None when no remote points at a known forge. */
	repo: ForgeRepo | null,
	/**  This build can talk to `repo.kind` (GitHub only for now). */
	supported: boolean,
	tokenSource: ForgeTokenSource,
};

export type ForgeTokenSource = "forge" | "gitCredential" | "none";

export type ForgeUser = {
	login: string,
};

export type GitIdentity = {
	name: string | null,
	email: string | null,
};

/**  Edge drawn from this row down to the next row. */
export type GraphEdge = {
	fromLane: number,
	toLane: number,
	kind: EdgeKind,
	color: number,
};

export type GraphFilter = {
	/**  `None` = all refs; otherwise short or full ref names to start the walk from. */
	refs: string[] | null,
	firstParent: boolean,
	order: CommitOrder,
	author: string | null,
	path: string | null,
	since: number | null,
	until: number | null,
};

export type GraphMeta = {
	rowCount: number,
	laneCount: number,
	headRow: number | null,
	/**  Lane color of every non-stash ref whose commit is in this graph, sorted by full name. */
	refColors: RefColor[],
};

export type GraphRow = {
	index: number,
	oid: string,
	shortOid: string,
	summary: string,
	authorName: string,
	authorEmail: string,
	authorTime: number | null,
	parents: string[],
	lane: number,
	color: number,
	edges: GraphEdge[],
	refs: RefLabel[],
};

export type GraphSearch = {
	/**  Matches message, author, or oid prefix. */
	text: string,
	maxResults: number,
};

export type HeadState = { kind: "branch"; name: string; oid: string } | { kind: "detached"; oid: string } | { kind: "unborn"; name: string };

export type Hunk = {
	header: string,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	lines: DiffLine[],
};

/**
 *  Selects part of a file diff. `lines = None` selects the whole hunk;
 *  otherwise indices into `Hunk.lines`.
 */
export type HunkSelection = {
	hunkIndex: number,
	lines: number[] | null,
};

export type InitRequest = {
	path: string,
	bare: boolean,
	initialBranch: string | null,
};

export type InteractiveRebaseRequest = {
	/**  Exclusive base commit; items apply on top of it. */
	base: string,
	todo: RebaseTodoItem[],
};

export type Issue = {
	number: number,
	title: string,
	state: IssueState,
	author: ForgeUser,
	labels: string[],
	comments: number,
	createdAt: number | null,
	updatedAt: number | null,
	/**  Web URL of the issue. */
	url: string,
};

export type IssueCreateRequest = {
	title: string,
	body: string,
};

export type IssueDetail = {
	issue: Issue,
	body: string,
	comments: ForgeComment[],
};

export type IssuePage = {
	items: Issue[],
	nextPage: number | null,
};

export type IssueQuery = {
	state: IssueStateFilter,
	page: number,
	perPage: number,
};

export type IssueState = "open" | "closed";

export type IssueStateFilter = "open" | "closed" | "all";

export type Keybinding = {
	action: string,
	keys: string,
};

export type KnownRepo = {
	path: string,
	name: string,
	lastOpened: number | null,
	/**  The folder still exists on disk. */
	exists: boolean,
};

export type LineKind = "context" | "add" | "delete" | 
/**  "\ No newline at end of file" marker. */
"noNewline";

/**
 *  `hunk_index`/`lines` refer to the diff produced with exactly `options`
 *  (the backend re-diffs with them). Staging requires
 *  `options.ignore_whitespace == false`.
 */
export type LineSelection = {
	path: string,
	options: DiffOptions,
	hunks: HunkSelection[],
};

export type MergeRequest = {
	/**  Ref or oid merged into HEAD (or into `into` when set). */
	source: string,
	/**  Branch to merge into; checked out first when it is not HEAD. */
	into: string | null,
	strategy: MergeStrategy,
	message: string | null,
};

export type MergeStrategy = "auto" | "noFf" | "ffOnly" | "squash";

export type OpFinished = OpFinishedPayload;

export type OpFinishedPayload = {
	opId: string,
	outcome: OpOutcome | null,
	error: AppError | null,
};

/**  Outcome of every mutating command. */
export type OpOutcome = { kind: "preview"; preview: OpPreview } | { kind: "applied"; oplogId: string; head: HeadState; message: string } | { kind: "conflicted"; oplogId: string; files: string[] };

/**  Result of a `dry_run`, shown in every confirmation dialog. */
export type OpPreview = {
	summary: string,
	refUpdates: RefUpdate[],
	commitsCreated: number,
	commitsDropped: CommitSummary[],
	predictedConflicts: string[],
	warnings: string[],
};

export type OpProgress = {
	opId: string,
	phase: string,
	percent: number | null,
	message: string | null,
};

export type OplogEntry = {
	id: string,
	time: number | null,
	/**  Command name, e.g. `merge`, `rebase_interactive`. */
	operation: string,
	description: string,
	headBefore: string | null,
	headAfter: string | null,
	undone: boolean,
};

export type OplogState = {
	canUndo: boolean,
	canRedo: boolean,
	/**  Description of the entry `undo` would revert. */
	undoDescription: string | null,
	redoDescription: string | null,
};

/**  The only operations an AI plan may contain. */
export type PlannedCommand = { kind: "checkout"; target: CheckoutTarget } | { kind: "branchCreate"; request: BranchCreateRequest } | { kind: "merge"; request: MergeRequest } | { kind: "rebase"; request: RebaseRequest } | { kind: "cherryPick"; request: CherryPickRequest } | { kind: "revert"; request: RevertRequest } | { kind: "reset"; request: ResetRequest } | { kind: "tagCreate"; request: TagCreateRequest } | { kind: "stashSave"; request: StashSaveRequest } | { kind: "fetch"; request: FetchRequest } | { kind: "pull"; request: PullRequest } | { kind: "push"; request: PushRequest };

export type PlannedStep = {
	description: string,
	command: PlannedCommand,
};

/**  Compile-time platform facts the UI uses to hide unsupported features. */
export type PlatformInfo = {
	/**  `std::env::consts::OS`: "android" | "windows" | "macos" | "linux". */
	os: string,
	mobile: boolean,
	hasGitCli: boolean,
	canPickFolder: boolean,
	supportsSsh: boolean,
	supportsExternalEditor: boolean,
	supportsRebase: boolean,
	supportsInteractiveRebase: boolean,
	supportsWorktrees: boolean,
	supportsSubmodules: boolean,
	supportsFileHistory: boolean,
	supportsHooks: boolean,
	readOnly: boolean,
	supportsTerminal: boolean,
	/**  "file" or "keychain". */
	secretStore: string,
	/**  Where clones land by default on mobile/embedded builds. */
	defaultReposDir: string | null,
};

export type PullBranch = {
	/**  Branch name, e.g. "feature/login". */
	name: string,
	/**  "owner:branch" as GitHub shows it. */
	label: string,
	sha: string,
	/**  "owner/name" of the repository holding the branch; None when it was deleted. */
	repo: string | null,
	/**  The branch lives in another repository than the base. */
	isFork: boolean,
};

export type PullDetail = {
	pull: ForgePull,
	/**  Plain text as written (Markdown source); never rendered as HTML. */
	body: string,
	/**  Conversation comments (not review comments). */
	comments: ForgeComment[],
	commits: number,
	additions: number,
	deletions: number,
	changedFiles: number,
	/**  None while GitHub is still computing it. */
	mergeable: boolean | null,
};

export type PullPage = {
	items: ForgePull[],
	nextPage: number | null,
};

export type PullQuery = {
	state: PullStateFilter,
	page: number,
	perPage: number,
};

export type PullRequest = {
	remote: string | null,
	branch: string | null,
	strategy: PullStrategy,
};

export type PullState = "open" | "closed" | "merged";

export type PullStateFilter = "open" | "closed" | "all";

export type PullStrategy = "merge" | "rebase" | "ffOnly";

export type PushRequest = {
	remote: string,
	refspecs: string[],
	forceWithLease: boolean,
	setUpstream: boolean,
	tags: boolean,
};

export type RebaseAction = "pick" | "reword" | "edit" | "squash" | "fixup" | "drop";

export type RebaseRequest = {
	onto: string,
	/**  Branch to rebase; defaults to HEAD. */
	branch: string | null,
};

export type RebaseTodoItem = {
	action: RebaseAction,
	oid: string,
	summary: string,
	/**  New message for `reword`, or combined message for `squash`. */
	message: string | null,
};

export type RecentRepo = {
	path: string,
	name: string,
	lastOpened: number | null,
};

export type RefColor = {
	fullName: string,
	color: number,
};

export type RefKind = "localBranch" | "remoteBranch" | "tag" | "stash";

export type RefLabel = {
	name: string,
	fullName: string,
	kind: RefKind,
	isHead: boolean,
};

export type RefMoveRequest = {
	/**  Full or short branch/tag name. */
	name: string,
	target: string,
	force: boolean,
};

export type RefUpdate = {
	name: string,
	from: string | null,
	to: string | null,
};

export type ReflogEntry = {
	index: number,
	oldOid: string,
	newOid: string,
	message: string,
	committer: Signature,
};

export type RefsSnapshot = {
	head: HeadState,
	local: BranchInfo[],
	remote: BranchInfo[],
	tags: TagInfo[],
	stashes: StashEntry[],
};

export type RemoteAddRequest = {
	name: string,
	url: string,
	fetch: boolean,
};

export type RemoteInfo = {
	name: string,
	fetchUrl: string,
	pushUrl: string | null,
	provider: RemoteProvider,
};

export type RemoteProvider = "gitHub" | "gitLab" | "bitbucket" | "azureDevOps" | "other";

export type RepoChanged = {
	repoId: string,
	scopes: ChangeScope[],
};

export type RepoInfo = {
	id: string,
	path: string,
	name: string,
	head: HeadState,
	state: RepoState,
	isBare: boolean,
};

export type RepoState = "clean" | "merge" | "revert" | "cherryPick" | "bisect" | "rebase" | "rebaseInteractive" | "applyMailbox";

export type ResetMode = "soft" | "mixed" | "hard";

export type ResetRequest = {
	target: string,
	mode: ResetMode,
};

export type RevertRequest = {
	commits: string[],
	noCommit: boolean,
};

export type SequencerAction = "continue" | "skip" | "abort";

export type Signature = {
	name: string,
	email: string,
	time: number | null,
	offsetMinutes: number,
};

export type SshKey = {
	/**  File stem, e.g. "id_ed25519". */
	name: string,
	/**  Path of the private key file (it may not exist, see has_private_key). */
	path: string,
	/**  The whole public key line ("ssh-ed25519 AAAA... comment"). */
	publicKey: string,
	/**  e.g. "ssh-ed25519", "ssh-rsa", "ecdsa-sha2-nistp256". */
	algorithm: string,
	/**  "SHA256:..." */
	fingerprint: string,
	comment: string,
	hasPrivateKey: boolean,
};

export type SshKeyGenerateRequest = {
	/**  File stem to create in ~/.ssh, e.g. "id_ed25519_gittrunk". */
	name: string,
	comment: string,
	/**  None or empty = unencrypted private key. */
	passphrase: string | null,
};

export type SshKeyList = {
	/**  The ~/.ssh directory (it may not exist yet). */
	dir: string,
	keys: SshKey[],
};

export type StashEntry = {
	index: number,
	oid: string,
	message: string,
	branch: string | null,
	time: number | null,
};

export type StashSaveRequest = {
	message: string | null,
	includeUntracked: boolean,
	keepIndex: boolean,
};

export type StatusSnapshot = {
	state: RepoState,
	staged: FileChange[],
	unstaged: FileChange[],
	conflicted: FileChange[],
};

export type SubmoduleInfo = {
	name: string,
	path: string,
	url: string | null,
	headOid: string | null,
	status: SubmoduleStatus,
};

export type SubmoduleStatus = "uninitialized" | "upToDate" | "modified" | "outOfDate";

export type SubmoduleUpdateRequest = {
	/**  Empty = all submodules. */
	paths: string[],
	init: boolean,
	recursive: boolean,
};

export type SummaryTarget = { kind: "commit"; oid: string } | { kind: "branch"; name: string; base: string };

export type TagCreateRequest = {
	name: string,
	target: string,
	/**  `Some` creates an annotated tag. */
	message: string | null,
};

export type TagInfo = {
	name: string,
	/**  Peeled commit id. */
	oid: string,
	annotated: boolean,
	message: string | null,
};

export type TerminalExit = {
	id: string,
	code: number | null,
};

export type TerminalOpenRequest = {
	cwd: string,
	cols: number,
	rows: number,
};

export type TerminalOutput = {
	id: string,
	data: string,
};

export type ThemePreference = "dark" | "light" | "system";

/**  A named group of repositories shown on the Home page. */
export type Workspace = {
	id: string,
	name: string,
	/**  Repository paths, in display order. */
	repos: string[],
};

export type WorktreeAddRequest = {
	path: string,
	branch: string,
	createBranch: boolean,
};

export type WorktreeInfo = {
	path: string,
	branch: string | null,
	head: string | null,
	isMain: boolean,
	locked: boolean,
	prunable: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

