import { useState, type ReactNode } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/design/components";
import { usePreviewedRun } from "@/features/ai/usePreviewedRun";

/** Base branch for summaries and PR drafts: the branch's upstream, else `main`. */
export function baseFor(upstream: string | null): string {
  return upstream ?? "main";
}

/** "Summarize branch" from a menu: payload preview on first use, then the summary in a dialog. */
export function useBranchSummary(repoId: string): {
  summarize: (name: string, base: string) => Promise<void>;
  dialog: ReactNode;
} {
  const { start, dialog: preview } = usePreviewedRun(repoId);
  const [result, setResult] = useState<{ name: string; text: string } | null>(null);

  const summarize = async (name: string, base: string) => {
    const text = await start({ kind: "summarize", target: { kind: "branch", name, base } });
    if (text) setResult({ name, text });
  };

  const dialog = (
    <>
      {preview}
      <Dialog open={result !== null} onOpenChange={(o) => !o && setResult(null)}>
        <DialogContent className="max-w-xl">
          <DialogHeader>
            <DialogTitle>Summary of {result?.name}</DialogTitle>
            <DialogDescription>Generated by AI; check it before relying on it.</DialogDescription>
          </DialogHeader>
          <p className="max-h-80 overflow-auto whitespace-pre-wrap text-base">{result?.text}</p>
        </DialogContent>
      </Dialog>
    </>
  );
  return { summarize, dialog };
}
